# Generated by Django 5.2.7 on 2025-12-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalkingRoute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('surface', models.CharField(blank=True, max_length=50, null=True)),
                ('smoothness', models.CharField(blank=True, max_length=50, null=True)),
                ('is_accessible', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'walking_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(help_text="Short code/label, e.g. 'blocked_ramp', 'broken_pavement'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional free-text description of the issue')),
                ('lat', models.FloatField(help_text='Latitude (WGS84)')),
                ('lng', models.FloatField(help_text='Longitude (WGS84)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.walkingroute')),
            ],
            options={
                'db_table': 'access_issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
